# Generated by Django 5.2.1 on 2025-08-07 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("description", models.TextField(verbose_name="Mô tả")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Giá"
                    ),
                ),
                ("area", models.FloatField(verbose_name="Diện tích (m²)")),
                (
                    "bedrooms",
                    models.IntegerField(default=0, verbose_name="Số phòng ngủ"),
                ),
                (
                    "bathrooms",
                    models.IntegerField(default=0, verbose_name="Số phòng tắm"),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Địa chỉ")),
                ("ward", models.CharField(max_length=100, verbose_name="Phường/Xã")),
                (
                    "district",
                    models.CharField(max_length=100, verbose_name="Quận/Huyện"),
                ),
                (
                    "city",
                    models.CharField(max_length=100, verbose_name="Tỉnh/Thành phố"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Có sẵn"),
                            ("sold", "Đã bán"),
                            ("reserved", "Đã đặt cọc"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Nổi bật"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Vĩ độ"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Kinh độ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bất động sản",
                "verbose_name_plural": "Bất động sản",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên tiện ích")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon class"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiện ích",
                "verbose_name_plural": "Tiện ích",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Loại hình bất động sản"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Loại hình bất động sản",
                "verbose_name_plural": "Loại hình bất động sản",
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="properties/", verbose_name="Hình ảnh"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Chú thích"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Ảnh chính"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hình ảnh bất động sản",
                "verbose_name_plural": "Hình ảnh bất động sản",
            },
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.propertytype",
                verbose_name="Loại hình",
            ),
        ),
        migrations.CreateModel(
            name="PropertyFeatureRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.propertyfeature",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiện ích bất động sản",
                "verbose_name_plural": "Tiện ích bất động sản",
                "unique_together": {("property", "feature")},
            },
        ),
    ]
