# Generated by Django 5.2.1 on 2025-08-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Họ và tên")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Số điện thoại"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Tin nhắn")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Mới"),
                            ("contacted", "Đã liên hệ"),
                            ("completed", "Hoàn thành"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Liên hệ",
                "verbose_name_plural": "Liên hệ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày đăng ký"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
            ],
            options={
                "verbose_name": "Đăng ký nhận tin",
                "verbose_name_plural": "Đăng ký nhận tin",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
